import React, { useState, useRef } from 'react';
import { generateVideo } from '../services/genai';
import { AspectRatio, GenerationStatus } from '../types';

const TEMPLATES = [
  {
    title: "Cyberpunk City",
    emoji: "🌃",
    prompt: "A cinematic drone shot flying through a futuristic cyberpunk city at night, with neon signs, flying cars, and rain-slicked streets. 8k resolution, highly detailed."
  },
  {
    title: "Serene Nature",
    emoji: "🌿",
    prompt: "A peaceful morning in a misty forest, sun rays piercing through the trees, illuminating a gentle stream. Photorealistic, 4k, calm atmosphere."
  },
  {
    title: "Space Odyssey",
    emoji: "🚀",
    prompt: "A majestic spaceship orbiting a giant ringed planet with a colorful nebula in the background. Sci-fi movie style, epic scale."
  },
  {
    title: "Cute Character",
    emoji: "🦊",
    prompt: "A cute, fluffy 3D animated fox character sitting in a magical library reading a glowing book. Pixar style, warm lighting."
  }
];

interface VideoGeneratorProps {
  isOffline: boolean;
}

type ExportFormat = 'MP4' | 'GIF';
type ExportResolution = 'original' | 'low';

const VideoGenerator: React.FC<VideoGeneratorProps> = ({ isOffline }) => {
  const [prompt, setPrompt] = useState('');
  const [aspectRatio, setAspectRatio] = useState<AspectRatio>(AspectRatio.LANDSCAPE);
  const [imageFile, setImageFile] = useState<File | null>(null);
  const [status, setStatus] = useState<GenerationStatus>('idle');
  const [videoUrl, setVideoUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  
  // Export states
  const [isExporting, setIsExporting] = useState(false);
  const [exportFormat, setExportFormat] = useState<ExportFormat>('MP4');
  const [exportResolution, setExportResolution] = useState<ExportResolution>('original');
  const [exportStatus, setExportStatus] = useState<string>('');

  const fileInputRef = useRef<HTMLInputElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setImageFile(e.target.files[0]);
    }
  };

  const handleGenerate = async () => {
    if (!prompt && !imageFile) return;
    if (isOffline) return;

    setStatus('processing');
    setError(null);
    setVideoUrl(null);
    setExportStatus('');

    try {
      const url = await generateVideo(prompt, aspectRatio === AspectRatio.LANDSCAPE ? '16:9' : '9:16', imageFile || undefined);
      setVideoUrl(url);
      setStatus('completed');
    } catch (err: any) {
      console.error(err);
      setError(err.message || "Failed to generate video");
      setStatus('failed');
      
      // Handle the specific "Requested entity was not found" error for API keys
      if (err.message && err.message.includes("Requested entity was not found")) {
        if (window.aistudio && window.aistudio.openSelectKey) {
             window.aistudio.openSelectKey();
        }
      }
    }
  };

  const handleDownload = async () => {
    if (!videoUrl) return;
    setIsExporting(true);
    setExportStatus('Preparing download...');

    try {
      if (exportFormat === 'MP4') {
        // Direct MP4 download
        const response = await fetch(videoUrl);
        if (!response.ok) throw new Error('Failed to fetch video file');
        const blob = await response.blob();
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `veo-generation-${Date.now()}.mp4`;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
        setExportStatus('Download started');
      } else if (exportFormat === 'GIF') {
        setExportStatus('Rendering GIF... (this may take a moment)');
        
        // Calculate dimensions based on resolution choice
        let width = 640; // Default reasonable width for GIF
        if (exportResolution === 'low') width = 320;
        
        // Use aspect ratio to determine height
        const height = aspectRatio === AspectRatio.LANDSCAPE 
            ? Math.round(width * 9 / 16) 
            : Math.round(width * 16 / 9);

        if (window.gifshot) {
            window.gifshot.createGIF({
                video: [videoUrl],
                gifWidth: width,
                gifHeight: height,
                interval: 0.1, // 10fps
                numFrames: 30, // Limit frames to keep processing manageable
                text: 'Generated by Veo',
                fontWeight: 'bold',
                fontSize: '16px',
                fontColor: '#ffffff',
                textAlign: 'center',
                textBaseline: 'bottom',
                sampleInterval: 10,
                numWorkers: 2,
            }, (obj: any) => {
                if (!obj.error) {
                    const image = obj.image;
                    const a = document.createElement('a');
                    a.href = image;
                    a.download = `veo-animation-${Date.now()}.gif`;
                    document.body.appendChild(a);
                    a.click();
                    document.body.removeChild(a);
                    setExportStatus('GIF Downloaded');
                } else {
                    throw new Error('GIF generation failed: ' + obj.errorCode);
                }
                setIsExporting(false);
            });
            // Return early as gifshot is async with callback
            return;
        } else {
            throw new Error('GIF library not loaded');
        }
      }
    } catch (e: any) {
      console.error(e);
      setExportStatus(`Error: ${e.message}`);
    } finally {
      if (exportFormat !== 'GIF') {
          setIsExporting(false);
      }
    }
  };

  const clearImage = () => {
    setImageFile(null);
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  return (
    <div className="flex flex-col h-full space-y-6">
      <div className="flex flex-col lg:flex-row gap-6">
        
        {/* Controls */}
        <div className="w-full lg:w-1/3 space-y-6 bg-gray-800 p-6 rounded-xl border border-gray-700">
          <h2 className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-pink-400">
            Configure Generation
          </h2>

          {/* Mode Indicator */}
          <div className="text-sm text-gray-400">
            Mode: <span className="text-white font-medium">{imageFile ? "Image-to-Video" : "Text-to-Video"}</span>
          </div>

          {/* Templates */}
          <div className={isOffline ? 'opacity-50 pointer-events-none' : ''}>
            <label className="block text-sm font-medium text-gray-300 mb-2">Quick Templates</label>
            <div className="grid grid-cols-2 gap-2">
              {TEMPLATES.map((t) => (
                <button
                  key={t.title}
                  onClick={() => setPrompt(t.prompt)}
                  disabled={isOffline}
                  className="flex items-center gap-2 px-3 py-2 bg-gray-900/50 hover:bg-gray-700 border border-gray-700 hover:border-purple-500/50 rounded-lg transition-all text-left group disabled:cursor-not-allowed"
                >
                  <span className="text-lg">{t.emoji}</span>
                  <span className="text-xs font-medium text-gray-300 group-hover:text-white truncate">{t.title}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Prompt Input */}
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-300">Prompt</label>
            <textarea
              className="w-full bg-gray-900 border border-gray-700 rounded-lg p-3 text-white focus:ring-2 focus:ring-purple-500 focus:outline-none resize-none h-32 disabled:opacity-50"
              placeholder={imageFile ? "Describe how to animate this image..." : "Describe a video scene..."}
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              disabled={isOffline}
            />
          </div>

          {/* Image Upload */}
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-300">Reference Image (Optional)</label>
            {!imageFile ? (
              <div 
                onClick={() => !isOffline && fileInputRef.current?.click()}
                className={`border-2 border-dashed border-gray-600 rounded-lg p-6 text-center transition-colors ${isOffline ? 'cursor-not-allowed opacity-50' : 'cursor-pointer hover:bg-gray-700/50'}`}
              >
                <input 
                  type="file" 
                  ref={fileInputRef} 
                  className="hidden" 
                  accept="image/*" 
                  onChange={handleFileChange} 
                  disabled={isOffline}
                />
                <svg className="w-8 h-8 mx-auto text-gray-500 mb-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                </svg>
                <p className="text-xs text-gray-400">Click to upload source image</p>
              </div>
            ) : (
              <div className="relative group">
                <img 
                  src={URL.createObjectURL(imageFile)} 
                  alt="Reference" 
                  className="w-full h-48 object-cover rounded-lg border border-gray-600 opacity-80"
                />
                {!isOffline && (
                  <button 
                    onClick={clearImage}
                    className="absolute top-2 right-2 bg-red-500/80 hover:bg-red-600 text-white p-1 rounded-full opacity-0 group-hover:opacity-100 transition-opacity"
                  >
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" /></svg>
                  </button>
                )}
              </div>
            )}
          </div>

          {/* Aspect Ratio */}
          <div className="space-y-2">
             <label className="block text-sm font-medium text-gray-300">Aspect Ratio</label>
             <div className={`flex bg-gray-900 p-1 rounded-lg ${isOffline ? 'opacity-50' : ''}`}>
               <button
                 onClick={() => setAspectRatio(AspectRatio.LANDSCAPE)}
                 disabled={isOffline}
                 className={`flex-1 py-2 text-sm font-medium rounded-md transition-all ${aspectRatio === AspectRatio.LANDSCAPE ? 'bg-gray-700 text-white shadow' : 'text-gray-400 hover:text-white'}`}
               >
                 Landscape (16:9)
               </button>
               <button
                 onClick={() => setAspectRatio(AspectRatio.PORTRAIT)}
                 disabled={isOffline}
                 className={`flex-1 py-2 text-sm font-medium rounded-md transition-all ${aspectRatio === AspectRatio.PORTRAIT ? 'bg-gray-700 text-white shadow' : 'text-gray-400 hover:text-white'}`}
               >
                 Portrait (9:16)
               </button>
             </div>
          </div>

          <button
            onClick={handleGenerate}
            disabled={status === 'processing' || (!prompt && !imageFile) || isOffline}
            className={`w-full py-3 rounded-lg font-bold text-white transition-all shadow-lg
              ${isOffline 
                ? 'bg-gray-700 cursor-not-allowed text-gray-400' 
                : status === 'processing'
                  ? 'bg-gray-600 cursor-wait'
                  : 'bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500 hover:shadow-purple-500/25'
              }
              disabled:opacity-50 disabled:shadow-none
            `}
          >
            {isOffline 
              ? 'Offline - Internet Required' 
              : status === 'processing' 
                ? 'Generating Video...' 
                : 'Generate with Veo'
            }
          </button>
          
          {error && (
            <div className="p-3 bg-red-900/50 border border-red-700 rounded-lg text-red-200 text-sm">
              {error}
            </div>
          )}
        </div>

        {/* Preview / Result Area */}
        <div className="flex-1 flex flex-col gap-4">
            <div className="flex-1 bg-black rounded-xl border border-gray-800 overflow-hidden flex items-center justify-center min-h-[400px] relative">
            {status === 'idle' && (
                <div className="text-center text-gray-500">
                <svg className="w-16 h-16 mx-auto mb-4 opacity-30" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z" />
                </svg>
                <p>Configure settings and click generate to see preview</p>
                </div>
            )}

            {status === 'processing' && (
                <div className="text-center">
                <div className="inline-block animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-purple-500 mb-4"></div>
                <p className="text-purple-300 animate-pulse">Creating your video with Veo...</p>
                <p className="text-xs text-gray-500 mt-2">This may take a minute.</p>
                </div>
            )}

            {status === 'completed' && videoUrl && (
                <video 
                    ref={videoRef}
                    controls 
                    autoPlay 
                    loop 
                    crossOrigin="anonymous" 
                    className="max-w-full max-h-full w-auto h-auto shadow-2xl"
                    src={videoUrl}
                />
            )}
            
            {status === 'failed' && (
                <div className="text-center text-gray-500">
                <svg className="w-16 h-16 mx-auto mb-4 text-red-500 opacity-50" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <p>Generation Failed</p>
            </div>
            )}
            </div>

            {/* Export Options */}
            {status === 'completed' && videoUrl && (
                <div className="bg-gray-800 rounded-xl border border-gray-700 p-4 animate-fade-in">
                    <h3 className="text-sm font-bold text-gray-300 mb-3 uppercase tracking-wider">Export Options</h3>
                    <div className="flex flex-col sm:flex-row gap-4 items-end">
                        <div className="space-y-1 flex-1">
                            <label className="text-xs text-gray-400">Format</label>
                            <div className="flex bg-gray-900 rounded-lg p-1">
                                <button 
                                    onClick={() => setExportFormat('MP4')}
                                    className={`flex-1 py-1.5 px-3 text-sm rounded-md transition-colors ${exportFormat === 'MP4' ? 'bg-gray-700 text-white shadow' : 'text-gray-400 hover:text-white'}`}
                                >
                                    MP4 Video
                                </button>
                                <button 
                                    onClick={() => setExportFormat('GIF')}
                                    className={`flex-1 py-1.5 px-3 text-sm rounded-md transition-colors ${exportFormat === 'GIF' ? 'bg-gray-700 text-white shadow' : 'text-gray-400 hover:text-white'}`}
                                >
                                    Animated GIF
                                </button>
                            </div>
                        </div>

                         <div className="space-y-1 flex-1">
                            <label className="text-xs text-gray-400">Resolution</label>
                            <div className="flex bg-gray-900 rounded-lg p-1">
                                <button 
                                    onClick={() => setExportResolution('original')}
                                    className={`flex-1 py-1.5 px-3 text-sm rounded-md transition-colors ${exportResolution === 'original' ? 'bg-gray-700 text-white shadow' : 'text-gray-400 hover:text-white'}`}
                                >
                                    Original
                                </button>
                                <button 
                                    onClick={() => setExportResolution('low')}
                                    className={`flex-1 py-1.5 px-3 text-sm rounded-md transition-colors ${exportResolution === 'low' ? 'bg-gray-700 text-white shadow' : 'text-gray-400 hover:text-white'}`}
                                >
                                    Low (Preview)
                                </button>
                            </div>
                        </div>

                        <button 
                            onClick={handleDownload}
                            disabled={isExporting}
                            className="w-full sm:w-auto px-6 py-2.5 bg-gray-700 hover:bg-gray-600 text-white rounded-lg font-medium transition-colors flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-wait"
                        >
                            {isExporting ? (
                                <span className="inline-block animate-spin rounded-full h-4 w-4 border-2 border-t-white border-white/20"></span>
                            ) : (
                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                            )}
                            {isExporting ? 'Processing...' : 'Download'}
                        </button>
                    </div>
                    {exportStatus && (
                        <div className="mt-2 text-xs text-gray-400 text-right">
                            {exportStatus}
                        </div>
                    )}
                </div>
            )}
        </div>
      </div>
    </div>
  );
};

export default VideoGenerator;